name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "2.6.10"
          - "2.7.7"
          - "3.0.5"
          - "3.1.3"
          - "3.2.1"
    services:
      postgres:
        image: postgres:14.5-alpine
        ports:
          - 5434:5432
        env:
          POSTGRES_USER: tines
          POSTGRES_DB: tines
          POSTGRES_PASSWORD: tines
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run spec
        run: bundle exec rspec
      - name: Run rubocop
        run: bundle exec rubocop
